Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,26 @@
-#!/usr/bin/env bash
-# This is a bash script that transfers a file from a client to a server using scp
+#!/bin/bash
 
-if [ "$#" -lt 3 ]; then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
-else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+# Check if all parameters are provided
+if [ "$#" -ne 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
+
+# Assign parameters to variables
+FILE_PATH="$1"
+SERVER_IP="$2"
+USERNAME="$3"
+SSH_KEY_PATH="$4"
+
+# Transfer file using scp
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
+
+# Check if scp command was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
+else
+    echo "Error: File transfer failed"
+    exit 1
+fi
+
+exit 0
